# Generated by Django 3.1.3 on 2021-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('author', models.CharField(default='admin', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.FileField(upload_to='blogs/')),
                ('content', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('author', models.CharField(default='admin', max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.FileField(upload_to='blogs/')),
                ('content', models.TextField(default='NA', max_length=1000)),
            ],
        ),
    ]
