# Generated by Django 3.1.3 on 2021-09-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogandnews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='heading',
        ),
    ]
