# Generated by Django 3.2.7 on 2021-10-04 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogandnews', '0006_auto_20210930_1405'),
        ('blogandnews', '0007_auto_20211002_1810'),
    ]

    operations = [
    ]
