# Generated by Django 3.2.7 on 2021-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogandnews', '0009_auto_20211009_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='mail',
            field=models.EmailField(default='tst@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
