# Generated by Django 3.2.7 on 2021-10-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogandnews', '0010_auto_20211009_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
    ]
