# Generated by Django 3.2.8 on 2021-10-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogandnews', '0012_blog_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
