# Generated by Django 3.2.8 on 2021-10-29 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='per',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.CreateModel(
            name='Bill_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill', verbose_name='items of bills')),
            ],
        ),
    ]
