# Generated by Django 3.2.7 on 2021-10-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=122)),
                ('phone', models.CharField(default='NA', max_length=12)),
                ('email', models.CharField(default='NA', max_length=122)),
                ('location', models.CharField(default='NA', max_length=12)),
                ('message', models.TextField(default='NA')),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Essentials', models.CharField(default='NA', max_length=12)),
                ('Premium', models.CharField(default='NA', max_length=12)),
                ('Luxe', models.CharField(default='NA', max_length=12)),
                ('countertop', models.CharField(default='NA', max_length=12)),
                ('HDHMR', models.CharField(default='NA', max_length=12)),
                ('MR_Plywood', models.CharField(default='NA', max_length=12)),
                ('BWR_Plywood', models.CharField(default='NA', max_length=12)),
                ('BWP_Plywood', models.CharField(default='NA', max_length=12)),
                ('Laminate', models.CharField(default='NA', max_length=12)),
                ('PVC_Laminate', models.CharField(default='NA', max_length=12)),
                ('Anti_scratch_Acrylic', models.CharField(default='NA', max_length=12)),
                ('Glossy_PU', models.CharField(default='NA', max_length=12)),
                ('Basic_Acc', models.CharField(default='NA', max_length=12)),
                ('Intermediate_Acc', models.CharField(default='NA', max_length=12)),
                ('Prem_Acc', models.CharField(default='NA', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='kitchen_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='NA', max_length=122)),
                ('Phone', models.CharField(default='NA', max_length=12)),
                ('Email', models.CharField(default='NA', max_length=122)),
                ('Shape', models.CharField(default='NA', max_length=12)),
                ('Size', models.CharField(default='NA', max_length=30, null=True)),
                ('Type', models.CharField(default='NA', max_length=30)),
                ('Material', models.CharField(default='NA', max_length=12)),
                ('Countertop', models.CharField(default='NA', max_length=12)),
                ('Loft', models.CharField(default='NA', max_length=12)),
                ('Finish', models.CharField(default='NA', max_length=12)),
                ('Accessories', models.CharField(default='NA', max_length=12)),
                ('Services', models.TextField(default='NA', max_length=132)),
                ('Appliances', models.TextField(default='NA', max_length=32)),
                ('Price', models.CharField(default='NA', max_length=12)),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
            ],
        ),
        migrations.CreateModel(
            name='City9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('date', models.DateField(default=1089)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
    ]
