# Generated by Django 3.2.7 on 2021-10-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen_details',
            name='Phone',
        ),
    ]
