# Generated by Django 3.2.7 on 2021-10-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_kitchen_details_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city1',
            name='kitchen',
        ),
    ]
