# Generated by Django 3.2.7 on 2021-10-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_city10_kitchen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city2',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city3',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city4',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city5',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city6',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city7',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city8',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city9',
            name='kitchen',
        ),
    ]
