# Generated by Django 3.2.7 on 2021-10-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211009_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city10',
            name='kitchen',
        ),
        migrations.AddField(
            model_name='city1',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city2',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city3',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city4',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city5',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city6',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city7',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city8',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
        migrations.AddField(
            model_name='city9',
            name='kitchen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details'),
        ),
    ]
