# Generated by Django 3.2.7 on 2021-10-10 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_city10_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_details',
            name='Appliances',
            field=models.TextField(default='NA', max_length=132),
        ),
        migrations.CreateModel(
            name='TempLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('kitchen_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
    ]
