# Generated by Django 3.2.7 on 2021-10-11 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211010_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('Location', models.CharField(default='NA', max_length=12)),
                ('kitchen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
        ),
        migrations.CreateModel(
            name='City11',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
    ]
