# Generated by Django 3.2.7 on 2021-10-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_city_city11'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city11',
            options={'verbose_name': 'Kolkata'},
        ),
    ]
