# Generated by Django 3.2.7 on 2021-10-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_city11_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city10',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city2',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city3',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city4',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city5',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city6',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city7',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city8',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='city9',
            name='kitchen',
        ),
        migrations.DeleteModel(
            name='City1',
        ),
        migrations.DeleteModel(
            name='City10',
        ),
        migrations.DeleteModel(
            name='City2',
        ),
        migrations.DeleteModel(
            name='City3',
        ),
        migrations.DeleteModel(
            name='City4',
        ),
        migrations.DeleteModel(
            name='City5',
        ),
        migrations.DeleteModel(
            name='City6',
        ),
        migrations.DeleteModel(
            name='City7',
        ),
        migrations.DeleteModel(
            name='City8',
        ),
        migrations.DeleteModel(
            name='City9',
        ),
        migrations.CreateModel(
            name='City1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City10',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City3',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City4',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City5',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City6',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City7',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City8',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City9',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
    ]
