# Generated by Django 3.2.7 on 2021-10-11 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211011_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city1',
            options={'verbose_name': 'Varanasi kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city10',
            options={'verbose_name': 'Sonbhadra kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city11',
            options={'verbose_name': 'Mirzapur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city2',
            options={'verbose_name': 'Chandauli kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city3',
            options={'verbose_name': 'Mirzapur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city4',
            options={'verbose_name': 'Sonbhadra kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city5',
            options={'verbose_name': 'Ayodhya kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city6',
            options={'verbose_name': 'Prayagraj kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city7',
            options={'verbose_name': 'Lucknow kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city8',
            options={'verbose_name': 'Bhadohi kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city9',
            options={'verbose_name': 'Gorakhpur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='kitchen_details',
            options={'managed': True, 'verbose_name': 'Kitchen Details', 'verbose_name_plural': 'Kitchen Details'},
        ),
        migrations.AlterModelTable(
            name='kitchen_details',
            table='',
        ),
        migrations.CreateModel(
            name='KitchenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/kitchen/')),
                ('kitchen', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.kitchen_details')),
            ],
            options={
                'verbose_name': 'Kitchen Image',
                'verbose_name_plural': 'Kitchen Images',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
