# Generated by Django 3.2.7 on 2021-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211012_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_details',
            name='Enquiry',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
