# Generated by Django 3.2.7 on 2021-10-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_kitchen_details_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_details',
            name='Address',
            field=models.TextField(default='', max_length=200),
        ),
    ]
