# Generated by Django 3.2.7 on 2021-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_kitchen_details_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen_details',
            name='Status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
