# Generated by Django 3.2.7 on 2021-10-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_kitchen_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City12',
            fields=[
            ],
            options={
                'verbose_name': 'Kanpur kitchen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='City13',
            fields=[
            ],
            options={
                'verbose_name': 'Jaunpur kitchen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
            ],
            options={
                'verbose_name': 'Other kitchen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.city',),
        ),
        migrations.AlterModelOptions(
            name='city10',
            options={'verbose_name': 'Ghazipur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city11',
            options={'verbose_name': 'Azamgarh kitchen'},
        ),
    ]
