# Generated by Django 3.2.7 on 2021-10-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20211013_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city10',
            options={'verbose_name': 'Ghazipur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city11',
            options={'verbose_name': 'Azamgarh kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city12',
            options={'verbose_name': 'Kanpur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city13',
            options={'verbose_name': 'Jaunpur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city3',
            options={'verbose_name': 'Mirzapur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city4',
            options={'verbose_name': 'Sonbhadra kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city5',
            options={'verbose_name': 'Ayodhya kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city6',
            options={'verbose_name': 'Prayagraj kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city7',
            options={'verbose_name': 'Lucknow kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city8',
            options={'verbose_name': 'Bhadohi kitchen'},
        ),
        migrations.AlterModelOptions(
            name='city9',
            options={'verbose_name': 'Gorakhpur kitchen'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'verbose_name': 'Other kitchen'},
        ),
    ]
