# Generated by Django 3.2.7 on 2021-10-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211013_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Location',
        ),
    ]
