# Generated by Django 3.1.3 on 2021-09-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Modular Kitchen', max_length=100)),
                ('descriptiom', models.TextField()),
                ('project_img', models.FileField(upload_to='projects/')),
                ('design_complete', models.BooleanField(default=False)),
                ('building_complete', models.BooleanField(default=False)),
                ('full_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
