# Generated by Django 3.2.7 on 2021-09-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210917_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
