# Generated by Django 3.2.7 on 2021-09-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210918_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='project',
        ),
    ]
