# Generated by Django 3.1.3 on 2021-09-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210919_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='project_name',
            field=models.CharField(default='Project', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='Client', max_length=100),
        ),
    ]
