# Generated by Django 3.2.7 on 2021-10-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210930_1405'),
        ('project', '0013_auto_20210930_1823'),
    ]

    operations = [
    ]
